### ISSUE TITLE
cml-py3 doesn't see GPU resources

### ISSUE THREAD

**Issue by pommedeterresautee** [iterative/cml#210]
When I try to run a train task on our AWS own infra the following error is raised on Github actions:
```
...
cfed3d9d6c7f: Pull complete
b5f3fa781593: Pull complete
53448e1579d7: Pull complete
c17eb7b4b5ac: Pull complete
25af3821284d: Pull complete
ea9f7c675b08: Pull complete
6522e7c5ced1: Pull complete
5fb2b6b033bf: Pull complete
1d90b6421d53: Pull complete
5d8a82854f4e: Pull complete
6fa3b0a92e5c: Pull complete
Digest: sha256:2e99adfe066a4383e3d391e5d4f1fbebc37b2c3d8f33ab883e810b35dd771965
Status: Downloaded newer image for dvcorg/cml-py3:latest
dfae88d60614134c3aeb2dc9095356b8cd545e1ad521f7db6575b518fe3ad679
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
About to remove cml1596929922
WARNING: This action will delete both local reference and remote instance.
Successfully removed cml1596929922
```

the workflow looks like this:

```yaml
name: train-model

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [service-catalog, linux, x64]
    container: docker://dvcorg/cml

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EC2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
        run: |
          echo "Deploying..."
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
          apt-get update && apt-get install -y nvidia-container-toolkit
          RUNNER_LABELS="cml,aws"
          RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
          MACHINE="cml$(date +%s)"
          docker-machine create \
            --driver amazonec2 \
            --amazonec2-instance-type g3s.xlarge \
            --amazonec2-vpc-id vpc-xxxxxxxx \
            --amazonec2-region eu-west-1 \
            --amazonec2-zone "a" \
            --amazonec2-ssh-user ubuntu \
            --amazonec2-ami ami-089cc16f7f08c4457 \
            --amazonec2-root-size 10 \
            $MACHINE
          eval "$(docker-machine env --shell sh $MACHINE)"
          (
          docker-machine ssh $MACHINE "sudo mkdir -p \
            /docker_machine && \
          sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ \
            $MACHINE:/docker_machine && \
          docker run --name runner --gpus all -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e DOCKER_MACHINE=$MACHINE \
            -e repo_token=$repo_token \
            -e RUNNER_LABELS=$RUNNER_LABELS \
            -e RUNNER_REPO=$RUNNER_REPO \
            -e RUNNER_IDLE_TIMEOUT=120 \
            dvcorg/cml-py3:latest && \
          sleep 20 && echo "Deployed $MACHINE"
          ) || (docker-machine rm -y -f $MACHINE && exit 1)
  train:
# ....
```

We run the tests on a self hosted runner.

**Comment by pommedeterresautee** [comment]
I have understood the issue. 
In the config above the AMI for the provisioned machine is a classic Ubuntu AMI instead of the ML dedicated one.
I had to change the AMI ID from the example because the ID from the example is not available in Ireland zone.
And to make Docker able to find GPU you need to have Nvidia drivers on the host plus a dedicated docker tool, etc.

I have found the right version of the ML AMI available in Ireland (the last updated one - version 27 - doesn't work): `ami-062ad6cd7428cb845`

My guess is that AWS has AMI dedicated to each zone.
May be it would make things easier if you your own tested AMI as suggested in https://github.com/iterative/cml/issues/162?

Now the deploy job is able to finish, I see the EC2 machine in the console but... the train tasks crash at the very beginning of the job (no log at all).

![image](https://user-images.githubusercontent.com/1029874/89733114-8fec7300-da53-11ea-9041-e3e41a0c8c0a.png)

![image](https://user-images.githubusercontent.com/1029874/89733140-b01c3200-da53-11ea-92b2-b1b3618f4eea.png)

Do you have an idea of the reason?

**Comment by DavidGOrtega** [comment]
> I have understood the issue.

You are totally right! 

> I have understood the issue.

Without seeing the workflow at least is very difficult. Could you please share it?

**Comment by pommedeterresautee** [comment]
Sure!
It's a a small adaptation from the official example.

```yaml
  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          apt-get update -y
          apt-get -y install python3 python3-venv python3-pip python3-setuptools build-essential git curl ca-certificates python3-dev
          # pip3 install dvc[s3]
          make setup_gpu_dev
          dvc pull resources/XXX
          make train_YYY
          # Report training parameters
          echo "## Training parameter diffs" >> report.md
          echo "```" >> report.md
          cat output/okdoc-pytorch/training_ZZZ.log
          echo "```" >> report.md
          cml-send-comment report.md
```

**Comment by DavidGOrtega** [comment]
@pommedeterresautee 

Your runner is being created to listed the tags ```RUNNER_LABELS="cml,aws"```
And your job is ```runs-on: [self-hosted,cml]```, so its missing a tag and there is not runner for it.

All the labels must be matched.

**Comment by pommedeterresautee** [comment]
My bad, I made plenty of experiences / run testing any parameter combination I had in mind, including not having all tags for the second container :) I should have posted another file.

Please find below the last version of the workflow (I am not using `aws` tag anymore), it's the one used to enter in the second container (`sleep 600` command, plus the deploy job is run on a self hosted runner registered on Github actions with the label `service-catalog`).
The result is always the same... deploy works but no new runner registered and train job is not performed.

```yaml
name: train-model

on:
  push:
    branches:
      - cml

jobs:
  deploy-cloud-runner:
    runs-on: [service-catalog, linux, x64]
    container: docker://dvcorg/cml
    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EC2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
        run: |
          echo "Deploying..."
          RUNNER_LABELS="cml"
          RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
          MACHINE="cml$(date +%s)"
          docker-machine create \
            --driver amazonec2 \
            --amazonec2-instance-type g3s.xlarge \
            --amazonec2-vpc-id vpc-XXX \
            --amazonec2-region eu-west-1 \
            --amazonec2-zone "a" \
            --amazonec2-ssh-user ubuntu \
            --amazonec2-ami ami-062ad6cd7428cb845 \
            --amazonec2-root-size 100 \
            $MACHINE
          eval "$(docker-machine env --shell sh $MACHINE)"

          (
          docker-machine ssh $MACHINE "sudo mkdir -p \
            /docker_machine && \
          sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ \
            $MACHINE:/docker_machine && \
          docker run --name runner --gpus all -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e DOCKER_MACHINE=$MACHINE \
            -e repo_token=$repo_token \
            -e RUNNER_LABELS=$RUNNER_LABELS \
            -e RUNNER_REPO=$RUNNER_REPO \
            -e RUNNER_IDLE_TIMEOUT=120 \
            dvcorg/cml-py3:latest && \
          sleep 20 && echo "Deployed $MACHINE"
          ) # || (docker-machine rm -y -f $MACHINE && exit 1)
          sleep 600
  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          apt-get update -y
          apt-get -y install python3 python3-venv python3-pip python3-setuptools build-essential git curl ca-certificates python3-dev
          make setup_gpu_dev

          dvc pull resources/xxx.tsv
          make train_xxx

          # Report training parameters
          echo "## Training parameter diffs" >> report.md
          echo "```" >> report.md
          cat output/okdoc-pytorch/training_xxx.log
          echo "```" >> report.md

          cml-send-comment report.md
```

What kind of file I can check to see if my container has github actions runner installed?

**Comment by DavidGOrtega** [comment]
@pommedeterresautee (love your nick)
i will check it

**Comment by DavidGOrtega** [comment]
@pommedeterresautee 

I have slightly modified your yaml. Its not wrong but the docker machine can fail during the creation and the cleanup should be performed to not waste money! 

```yaml
name: train-model

on:
  push:
    branches:
      - cml

jobs:
  deploy-cloud-runner:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml
    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EC2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
        run: |
          echo "Deploying..."
          RUNNER_LABELS="cml"
          RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
          MACHINE="cml$(date +%s)"

          (
          docker-machine create \
            --driver amazonec2 \
            --amazonec2-instance-type g3s.xlarge \
            --amazonec2-vpc-id vpc-XXX \
            --amazonec2-region eu-west-1 \
            --amazonec2-zone "a" \
            --amazonec2-ssh-user ubuntu \
            --amazonec2-ami ami-062ad6cd7428cb845 \
            --amazonec2-root-size 100 \
            $MACHINE
          eval "$(docker-machine env --shell sh $MACHINE)" && \

          docker-machine ssh $MACHINE "sudo mkdir -p \
            /docker_machine && \
          sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ \
            $MACHINE:/docker_machine && \

          docker run --name runner --gpus all -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e DOCKER_MACHINE=$MACHINE \
            -e repo_token=$repo_token \
            -e RUNNER_LABELS=$RUNNER_LABELS \
            -e RUNNER_REPO=$RUNNER_REPO \
            -e RUNNER_IDLE_TIMEOUT=120 \
            dvcorg/cml-py3:latest && \
          sleep 20 && echo "Deployed $MACHINE"
          ) || (docker-machine rm -y -f $MACHINE && exit 1)

  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml]
    steps:
      
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
        run: |
          apt-get update -y
          apt-get -y install python3 python3-venv python3-pip python3-setuptools build-essential git curl ca-certificates python3-dev
          make setup_gpu_dev

          dvc pull resources/xxx.tsv
          make train_xxx

          # Report training parameters
          echo "## Training parameter diffs" >> report.md
          echo "```" >> report.md
          cat output/okdoc-pytorch/training_xxx.log
          echo "```" >> report.md

          cml-send-comment report.md
```

Can you see the runner registering in your repo?

![image](https://user-images.githubusercontent.com/414967/89775729-b9b3a180-db08-11ea-8cdc-9e421c4faeb1.png)

I have tried a very similar yaml with success

**Comment by pommedeterresautee** [comment]
Tks a lot for your help.
I tried the workflow you posted with minor modification: restoring the real vpc ID and some filenames in the train jobs.
The result is the same, the train job is never launched.
I kept refreshing the Actions page open during the process to see but didn't see new self hosted runner.

* Any other idea? 
* Does it make sense that I don't see any trace of the runner folder in the second container?

**Comment by DavidGOrtega** [comment]
> I tried the workflow you posted with minor modifications

Im not expecting it to work

my first question is that the runner registers to the repo. Have a look in settings

**Comment by pommedeterresautee** [comment]
the whole time it stayed like that:
![image](https://user-images.githubusercontent.com/1029874/89785070-14092e00-db1a-11ea-9c99-7c6c0966e942.png)

**Comment by pommedeterresautee** [comment]
May be something of interest.
When run on my own runner, the logs are:
![image](https://user-images.githubusercontent.com/1029874/89785392-a14c8280-db1a-11ea-8e57-86656b2e8138.png)

When run on Github runner, the logs are:
![image](https://user-images.githubusercontent.com/1029874/89785473-c3de9b80-db1a-11ea-8d26-4a4a73f858ea.png)

It's a bit surprising as both are using the same AMI (I just changed the `on` clause).

**Comment by DavidGOrtega** [comment]
Im not using that ami. Im using ubuntu installing gpu drivers plus nvidia docker

**Comment by pommedeterresautee** [comment]
Which Ubuntu? 18.04?
Nvidia docker is `NVIDIA Container Toolkit` ?

**Comment by DavidGOrtega** [comment]
```
docker-machine ssh $MACHINE "sudo apt update && sudo apt install -y ubuntu-drivers-common && sudo ubuntu-drivers autoinstall" && \

docker-machine restart $MACHINE && \
eval "$(docker-machine env --shell sh $MACHINE)" && \

docker-machine ssh $MACHINE "curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list && sudo apt update && sudo apt install -y nvidia-container-toolkit && sudo systemctl restart docker" && \

docker run --name runner --gpus all -d \
...
```

**Comment by DavidGOrtega** [comment]
However said that... It looks like at some point the runner registers

**Comment by DavidGOrtega** [comment]
could be possible that you have actually a runner with that name somewhere else? What its that ```service-catalog```?
the  CML runner should be registering with a weird name

**Comment by DavidGOrtega** [comment]
> Which Ubuntu? 18.04?

Yes, my AMI is ami-085925f297f89fce1

**Comment by DavidGOrtega** [comment]
@pommedeterresautee can you share logs of the ```deploy-cloud-runner```  job ?

**Comment by pommedeterresautee** [comment]
have you an email where I can send it to you?

**Comment by DavidGOrtega** [comment]
g.ortega.david@gmail.com

**Comment by DavidGOrtega** [comment]
@pommedeterresautee 
did you created a personal repo token with repo and workflow permissions?

![image](https://user-images.githubusercontent.com/414967/89814696-d28d7880-db43-11ea-8040-4b09435a8f2a.png)

**Comment by pommedeterresautee** [comment]
The issue was indeed related to the token (its name was not matching anymore the workflow script).
Now it's fixed and the workflow works like a charm.
